export const searchData = {
  cities: ["Orlando", "Los Angeles", "Miami", "Denver", "Berlin", "London"],
  neighbourhoods: [
    "Downtown",
    "South Beach",
    "West End",
    "North Beach",
    "East End",
    "Central",
    "Northside",
    "Westside",
    "Southside",
    "Uptown",
    "Eastside",
  ],
  genres: [
    "Hip-Hop",
    "RnB",
    "Pop",
    "Rock",
    "Electronic",
    "Reggae",
    "Dance",
    "Jazz",
    "Country",
    "Folk",
    "Metal",
    "Punk",
    "Rap",
    "Soul",
    "Alternative",
    "Classical",
    "World",
    "Other",
  ],
  venues: [
    "Bar",
    "Club",
    "Lounge",
    "Nightclub",
    "Pub",
    "Restaurant",
    "Theater",
    "Other",
  ],
};
